mp4seek: rework versioning system
We used to depend on the cmake's "VERSION <version>" string
to define a unique version field. We are moving the version
numbering to a new file, include/mp4seek_version.h. This
will allow Android.bp to share the version number.

Changes:
- added include/mp4seek_version.h, the single source of truth
  for version and project name. Started at the current version
  (0.2).
- updated tools/mp4seek_main.cc to use the new version file
- updated CMakeLists.txt
- removed src/config.h.in (no longer used)

Tested:
```
$ cmake -DCMAKE_BUILD_TYPE=DEBUG -DUSE_MP4V2=ON  -DBUILD_TESTING=OFF ..
...
$ make -j
...
[100%] Built target mp4seek
$ ./mp4seek
Error: Both infile and outfile are required
mp4seek version 0.2
...
```